// gate-errors.ts — short, stable error codes returned verbatim in the { message }
// body. The ddocs.new client switches on HTTP status only, so these are for humans
// and logs reading the response. Server-internal throws (bad config, CAS contention)
// and logger lines stay descriptive — they only ever surface as a logged 500.
export const GateErrorCode = {
  // 400 — malformed request
  INVALID_PROOF_SHAPE: "INVALID_PROOF_SHAPE",
  UNENCODABLE_SIGNAL: "UNENCODABLE_SIGNAL",
  INVALID_ACCEPTED_ROOTS: "INVALID_ACCEPTED_ROOTS",
  CHAIN_ID_MISMATCH: "CHAIN_ID_MISMATCH",
  INVALID_DOC_ID: "INVALID_DOC_ID",
  INVALID_COMMITMENT: "INVALID_COMMITMENT",
  INVALID_GROUP_REF: "INVALID_GROUP_REF",
  INVALID_EVALUATION_REQUEST: "INVALID_EVALUATION_REQUEST",
  INVALID_REQUEST_BODY: "INVALID_REQUEST_BODY",

  // 401 — authentication
  INVALID_UCAN: "INVALID_UCAN",
  INVALID_PRIVY_TOKEN: "INVALID_PRIVY_TOKEN",
  VAULT_NO_SESSION: "VAULT_NO_SESSION",
  UCAN_REPLAYED: "UCAN_REPLAYED",

  // 403 — authorization
  PROOF_SCOPE_MISMATCH: "PROOF_SCOPE_MISMATCH",
  INVALID_PROOF: "INVALID_PROOF",
  NONCE_NOT_LIVE: "NONCE_NOT_LIVE",
  NOT_DOC_OWNER: "NOT_DOC_OWNER",
  MISSING_CAPABILITY: "MISSING_CAPABILITY",
  INVALID_VOUCHER: "INVALID_VOUCHER",
  VOUCHER_DOC_MISMATCH: "VOUCHER_DOC_MISMATCH",
  VOUCHER_GROUP_MISMATCH: "VOUCHER_GROUP_MISMATCH",
  INVALID_VOUCHER_ROLE: "INVALID_VOUCHER_ROLE",
  BIND_MISMATCH: "BIND_MISMATCH",
  CROSS_PORTAL_ATTACH: "CROSS_PORTAL_ATTACH",
  IDENTITY_REVOKED: "IDENTITY_REVOKED",
  VAULT_NOT_ENROLLED: "VAULT_NOT_ENROLLED",

  // 404
  DOC_NOT_REGISTERED: "DOC_NOT_REGISTERED",
  GROUP_NOT_REGISTERED: "GROUP_NOT_REGISTERED",
  GROUP_NOT_ATTACHED: "GROUP_NOT_ATTACHED",
  NOT_FOUND: "NOT_FOUND",

  // 409 — conflict
  ANCHOR_MISMATCH: "ANCHOR_MISMATCH",
  GROUP_ANCHOR_MISMATCH: "GROUP_ANCHOR_MISMATCH",
  STALE_GROUP_ROOT: "STALE_GROUP_ROOT",
  COMMITMENT_PINNED: "COMMITMENT_PINNED",
  STALE_EPOCH: "STALE_EPOCH",
  VAULT_KEY_VERSION_RETIRED: "VAULT_KEY_VERSION_RETIRED",

  // 415: unsupported request body type
  UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",

  // 429: rate limited
  RATE_LIMITED: "RATE_LIMITED",

  // 503 — unavailable
  GATE_NOT_READY: "GATE_NOT_READY",
  MASTER_KEY_NOT_CONFIGURED: "MASTER_KEY_NOT_CONFIGURED",
  UPSTREAM_UNAVAILABLE: "UPSTREAM_UNAVAILABLE",
  VAULT_KEY_NOT_CONFIGURED: "VAULT_KEY_NOT_CONFIGURED",
  VAULT_SIGNING_KEY_NOT_CONFIGURED: "VAULT_SIGNING_KEY_NOT_CONFIGURED",

  // 500
  SOMETHING_WENT_WRONG: "SOMETHING_WENT_WRONG",
} as const;
